# Generated by Django 5.0.1 on 2024-01-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafi', '0002_alter_human_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='gender',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
