# Generated by Django 5.0.1 on 2024-01-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nafi', '0003_alter_human_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='age',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
